### PR TITLE
Simplification of the web site

### PR DESCRIPTION
**Pull request by regisd**
- Remove duplicate content with change history
- Remove duplicate content with mailing lists
- Simplify navigation by pointing directly to github

### CODE REVIEW

**Comment by lsf37** [comment]
Thanks, very cool. High time this got consolidated a bit more.

I like all of the changes apart from be9bcc62326d5fa6d4f462eb24240c87c97cb07f, the merge of the changelog. I agree that there is duplication and it should be consolidated more than it is now, but the 3 lists serve 3 different purposes:
- `history.md` is the complete changelog and eventually should be copied over automatically from the main repo in the release process (should probably rename to just `changelog.md`)
- `features.md` was supposed to just be a list of high-level features. Over time it turned into something changelog-like and we should fix that, but I think we still want a separate thing for features (maybe not a separate page, though)
- the changelog part on `index.md` is there so you can quickly see what is new, i.e. high-level points for the last major feature release and the change log for the last point release

Do you think the 3 purposes make sense or would you argue it's not worth separating them?

**Comment by regisd** [comment]
So generally I think it is not useful to have redundant changelog. My gut
feeling is that there are basically three kinds of users:
- Those who always work with the latest version. They are maybe informed
  via jflex-announce, and when there is a new release, they check the
  changelog to see how the changes impact their code. They virtually don't
  need the change history, but only need the "what's new" for the new release.
- Those who upgrade from time to time. They didn't pay attention to the
  mailing-list, and need to understand what's breaking their code when they
  bump from version 3 to version 10.
- Those who upgrade only when they need a new feature. A full detailed
  history is critical for them too.

So yes:
- history.md should be comprehensive and renamed changelog.md
- I didn't delete feature.md, but may have removed too much content. It
  needs to present the features as they are today, there shoundnt be history
  there.
- I understand your point with index.md presenting the biggest new feature
  in the news section. Maybe the simple link to the changelog isn't enough,
  and we want to highlight what's new. That also shows the project is alive.

I'll update my change accordingly to this feedback. Thanks for having a
look.

I was also thinking about changing the nav to empahasis an help section.

Le dim. 12 avr. 2015 à 02:05, Gerwin Klein notifications@github.com a
écrit :

**Comment by lsf37** [comment]
Cool, I think we agree.

I misread the diff and thought you had removed `features.md` completely. If it's still there, we can tweak it incrementally later as well. Don't worry too much about this one.

**Comment by lsf37** [comment]
Awesome.

**Pull request merged**
