### PR TITLE
Remove border radius

### PR DESCRIPTION
**Pull request by kefala**
It was killing me to have that border. If you want, I can help with site design

### CODE REVIEW

**Comment by regisd** [comment]
Thanks for your proposing a patch.

What are you tring to fix? Is there a visual glitch? On which browser?

There is currently noborder-radius defined, hence the default of 0 should apply.

Can you attach a screenshot before/after, please.

Also, please improve description. In this case, the change doesn't remove the border radius, but instead sets it to zero.

**Comment by kefala** [comment]
### Site / Before

captura de pantalla 2016-09-13 a las 10 26 17 a m

### Fork / After

captura de pantalla 2016-09-13 a las 10 26 51 a m

It's just a suggestion only.

Bootstrap implements border-radius for their menu's

**Comment by lsf37** [comment]
The corners of the blue area are rounded, yes. I'm seeing the same in Safari. It's never bothered me before, but I'm happy with removing it.

**Comment by lsf37** [comment]
Now deployed on http://jflex.de. All sharp corners!

**Pull request merged**
